// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/node_modules/dumi-theme-antd/dist/slots/Sidebar/index.js';
