// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/mima1234/Desktop/fluxsum/node_modules/.bun/dumi@2.4.23+78013ad134a0fbb4/node_modules/dumi/theme-default/slots/Tabs/index.js';
