// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/accordion/index.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/accordion/index.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/action-icon-group/index.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/action-icon-group/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/action-icon/index.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/action-icon/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/alert-dialog/index.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/alert-dialog/index.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/alert/index.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/alert/index.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/avatar/index.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/avatar/index.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/badge/index.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/badge/index.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/breadcrumb/index.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/breadcrumb/index.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/button/index.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/button/index.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/card/index.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/card/index.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/checkbox/index.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/checkbox/index.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/collapse/index.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/collapse/index.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/copy-button/index.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/copy-button/index.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/divider/index.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/divider/index.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/drawer/index.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/drawer/index.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/dropdown/index.md?type=frontmatter';
import { demoIndex as dmi15 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/dropdown/index.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/empty/index.md?type=frontmatter';
import { demoIndex as dmi16 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/empty/index.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/flex/index.md?type=frontmatter';
import { demoIndex as dmi17 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/flex/index.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/form/index.md?type=frontmatter';
import { demoIndex as dmi18 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/form/index.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/group-avatar/index.md?type=frontmatter';
import { demoIndex as dmi19 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/group-avatar/index.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/hotkey/index.md?type=frontmatter';
import { demoIndex as dmi20 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/hotkey/index.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/input/index.md?type=frontmatter';
import { demoIndex as dmi21 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/input/index.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/label/index.md?type=frontmatter';
import { demoIndex as dmi22 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/label/index.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/list/index.md?type=frontmatter';
import { demoIndex as dmi23 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/list/index.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/modal/index.md?type=frontmatter';
import { demoIndex as dmi24 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/modal/index.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/pagination/index.md?type=frontmatter';
import { demoIndex as dmi25 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/pagination/index.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/popover/index.md?type=frontmatter';
import { demoIndex as dmi26 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/popover/index.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/progress/index.md?type=frontmatter';
import { demoIndex as dmi27 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/progress/index.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/radio-group/index.md?type=frontmatter';
import { demoIndex as dmi28 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/radio-group/index.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/scroll-area/index.md?type=frontmatter';
import { demoIndex as dmi29 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/scroll-area/index.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/search-bar/index.md?type=frontmatter';
import { demoIndex as dmi30 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/search-bar/index.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/select/index.md?type=frontmatter';
import { demoIndex as dmi31 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/select/index.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/separator/index.md?type=frontmatter';
import { demoIndex as dmi32 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/separator/index.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/skeleton/index.md?type=frontmatter';
import { demoIndex as dmi33 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/skeleton/index.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/slider/index.md?type=frontmatter';
import { demoIndex as dmi34 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/slider/index.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/snippet/index.md?type=frontmatter';
import { demoIndex as dmi35 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/snippet/index.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/spinner/index.md?type=frontmatter';
import { demoIndex as dmi36 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/spinner/index.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/statistic/index.md?type=frontmatter';
import { demoIndex as dmi37 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/statistic/index.md?type=demo-index';
import { frontmatter as fm38, toc as t38 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/switch/index.md?type=frontmatter';
import { demoIndex as dmi38 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/switch/index.md?type=demo-index';
import { frontmatter as fm39, toc as t39 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/table/index.md?type=frontmatter';
import { demoIndex as dmi39 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/table/index.md?type=demo-index';
import { frontmatter as fm40, toc as t40 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/tabs/index.md?type=frontmatter';
import { demoIndex as dmi40 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/tabs/index.md?type=demo-index';
import { frontmatter as fm41, toc as t41 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/tag/index.md?type=frontmatter';
import { demoIndex as dmi41 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/tag/index.md?type=demo-index';
import { frontmatter as fm42, toc as t42 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/text/index.md?type=frontmatter';
import { demoIndex as dmi42 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/text/index.md?type=demo-index';
import { frontmatter as fm43, toc as t43 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/timeline/index.md?type=frontmatter';
import { demoIndex as dmi43 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/timeline/index.md?type=demo-index';
import { frontmatter as fm44, toc as t44 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/toast/index.md?type=frontmatter';
import { demoIndex as dmi44 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/toast/index.md?type=demo-index';
import { frontmatter as fm45, toc as t45 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/tooltip/index.md?type=frontmatter';
import { demoIndex as dmi45 } from '/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/tooltip/index.md?type=demo-index';

export const filesMeta = {
  'components/accordion/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/accordion/index.md?type=text'),
  },
  'components/action-icon-group/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/action-icon-group/index.md?type=text'),
  },
  'components/action-icon/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/action-icon/index.md?type=text'),
  },
  'components/alert-dialog/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/alert-dialog/index.md?type=text'),
  },
  'components/alert/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/alert/index.md?type=text'),
  },
  'components/avatar/index': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/avatar/index.md?type=text'),
  },
  'components/badge/index': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/badge/index.md?type=text'),
  },
  'components/breadcrumb/index': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/breadcrumb/index.md?type=text'),
  },
  'components/button/index': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/button/index.md?type=text'),
  },
  'components/card/index': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/card/index.md?type=text'),
  },
  'components/checkbox/index': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/checkbox/index.md?type=text'),
  },
  'components/collapse/index': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/collapse/index.md?type=text'),
  },
  'components/copy-button/index': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/copy-button/index.md?type=text'),
  },
  'components/divider/index': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/divider/index.md?type=text'),
  },
  'components/drawer/index': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/drawer/index.md?type=text'),
  },
  'components/dropdown/index': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/dropdown/index.md?type=text'),
  },
  'components/empty/index': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/empty/index.md?type=text'),
  },
  'components/flex/index': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/flex/index.md?type=text'),
  },
  'components/form/index': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/form/index.md?type=text'),
  },
  'components/group-avatar/index': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/group-avatar/index.md?type=text'),
  },
  'components/hotkey/index': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/hotkey/index.md?type=text'),
  },
  'components/input/index': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/input/index.md?type=text'),
  },
  'components/label/index': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/label/index.md?type=text'),
  },
  'components/list/index': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/list/index.md?type=text'),
  },
  'components/modal/index': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/modal/index.md?type=text'),
  },
  'components/pagination/index': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/pagination/index.md?type=text'),
  },
  'components/popover/index': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/popover/index.md?type=text'),
  },
  'components/progress/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/progress/index.md?type=text'),
  },
  'components/radio-group/index': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/radio-group/index.md?type=text'),
  },
  'components/scroll-area/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/scroll-area/index.md?type=text'),
  },
  'components/search-bar/index': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/search-bar/index.md?type=text'),
  },
  'components/select/index': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/select/index.md?type=text'),
  },
  'components/separator/index': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/separator/index.md?type=text'),
  },
  'components/skeleton/index': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/skeleton/index.md?type=text'),
  },
  'components/slider/index': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/slider/index.md?type=text'),
  },
  'components/snippet/index': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/snippet/index.md?type=text'),
  },
  'components/spinner/index': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/spinner/index.md?type=text'),
  },
  'components/statistic/index': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/statistic/index.md?type=text'),
  },
  'components/switch/index': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/switch/index.md?type=text'),
  },
  'components/table/index': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/table/index.md?type=text'),
  },
  'components/tabs/index': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/tabs/index.md?type=text'),
  },
  'components/tag/index': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/tag/index.md?type=text'),
  },
  'components/text/index': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/text/index.md?type=text'),
  },
  'components/timeline/index': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/timeline/index.md?type=text'),
  },
  'components/toast/index': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/toast/index.md?type=text'),
  },
  'components/tooltip/index': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/mima1234/Desktop/fluxsum/packages/ui-kit/src/components/tooltip/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
